feat: Add proper foreign key connection for OrderService module RP-60
RePro3D-Praxisproject/repro3d-backend pull request #9
Opened 2024-04-13 22:24 UTC by LostPersona

## Description
This PR adds proper handling of the foreign key relationship in the OrderService module.
In order to do that the module includes Entity models of all referenced Entities (Printer.java and so on)

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (please describe):

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

2024-04-14 16:18 UTC, mahlibalazs requested changes
Check for snake case and camel case mixups, like in OrderService/src/main/java/repro3d/model/Order.java line 38.

2024-04-14 16:28 UTC, LostPersona commented
I have requested the review again, since I have renamed the referenced column names.

2024-04-15 08:23 UTC, mahlibalazs approved these changes

2024-04-15 20:43 UTC, Hosseinamir1989 approved these changes
Approved

2024-04-15 20:48 UTC, merged